### ISSUE TITLE
issue with cg2all

### ISSUE THREAD

**Issue by aashuph16221** [huhlim/cg2all#16]

**Comment by aashuph16221** [comment]
Hi,

i am using the cg2all convert CG pdb format into the all atom.
i got an error:


convert_cg2all -p 1ab1_A.martini.pdb -o my_all_atom.pdb 
Traceback (most recent call last):
  File "/home/aashish/.conda/envs/cg2all/bin/convert_cg2all", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aashish/.conda/envs/cg2all/lib/python3.11/site-packages/cg2all/script/convert_cg2all.py", line 190, in main
    batch = next(iter(input_s)).to(device)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/aashish/.conda/envs/cg2all/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/aashish/.conda/envs/cg2all/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aashish/.conda/envs/cg2all/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/aashish/.conda/envs/cg2all/lib/python3.11/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
dgl._ffi.base.DGLError: Caught DGLError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/aashish/.conda/envs/cg2all/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/aashish/.conda/envs/cg2all/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aashish/.conda/envs/cg2all/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/aashish/.conda/envs/cg2all/lib/python3.11/site-packages/cg2all/lib/libdata.py", line 343, in __getitem__
    geom_s = cg.get_geometry(
             ^^^^^^^^^^^^^^^^
  File "/home/aashish/.conda/envs/cg2all/lib/python3.11/site-packages/cg2all/lib/libcg.py", line 136, in get_geometry
    graph = dgl.radius_graph(r, 1.0)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aashish/.conda/envs/cg2all/lib/python3.11/site-packages/dgl/transforms/functional.py", line 3533, in radius_graph
    raise DGLError("Find empty point set")
dgl._ffi.base.DGLError: Find empty point set

when i using  the alpha carbon file  then its running. 

cg2all -p ../1ab1_A.calpha.pdb -o my_all_atom.pdb

could you please help me how i can use cg to aa?

Regards,
