### ISSUE TITLE
Error installing cg2all 

### ISSUE THREAD

**Issue by TomMakkink** [huhlim/cg2all#2]
### Description 

When installing the cg2all package, there is an issue with the mdtraj dependency. 

### Steps to reproduce 

Simply install the CPU version of the package: 

```pip install git+http://github.com/huhlim/cg2all```

### Expected Behaviour 

Cg2all installs. 

### Actual Behaviour 

Here is part of the traceback of the error message: 

       Compiling mdtraj/geometry/neighborlist.pyx because it changed.
      [ 1/12] Cythonizing mdtraj/formats/binpos/binpos.pyx
      [ 2/12] Cythonizing mdtraj/formats/dcd/dcd.pyx
      [ 3/12] Cythonizing mdtraj/formats/dtr/dtr.pyx
      [ 4/12] Cythonizing mdtraj/formats/tng/tng.pyx
      [ 5/12] Cythonizing mdtraj/formats/xtc/trr.pyx
      [ 6/12] Cythonizing mdtraj/formats/xtc/xtc.pyx
      [ 7/12] Cythonizing mdtraj/geometry/drid.pyx
      [ 8/12] Cythonizing mdtraj/geometry/neighborlist.pyx
      [ 9/12] Cythonizing mdtraj/geometry/neighbors.pyx
      [10/12] Cythonizing mdtraj/geometry/src/_geometry.pyx
      Traceback (most recent call last):
        File "/home/marbesu/opt/mambaforge/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/marbesu/opt/mambaforge/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/marbesu/opt/mambaforge/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-_u4n_672/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-_u4n_672/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-_u4n_672/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 304, in <module>
        File "/tmp/pip-build-env-_u4n_672/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-_u4n_672/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: mdtraj/geometry/src/_geometry.pyx
      [end of output]

**Comment by huhlim** [comment]
Thank you for leaving this issue. Apparently, the MDTraj library is not compatible with the latest version of Cython library , which is released a couple of weeks a go. So, they constrained Cython version to an older version. https://github.com/mdtraj/mdtraj/commit/2ba38d830b89c33da37e291582ad289abf3a3ff4
I merged the changes in the original repository to my customized repository. I confirmed that the issue has been disappeared. So, please try it again.

**Comment by TomMakkink** [comment]
Works on my end as well! Thanks very much!
