### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by aminsagar** [huhlim/cg2all#5]
Hello.
Thanks for this awesome work.
I tried to install following the instructions.
The installation goes well, but when I try to convert the test systems, I get the following error.
I have tried different versions of cudatoolkit 11.3,11.6,11.7 and 11.8. 
I have also tried installing dgl from source but I get the same error.
Have you seen this before?

```
(cg2all) tambones@PC-EQA2-03:~/softwares/cg2all/tests$ convert_cg2all -p 1ab1_A.martini.pdb -o test_martini.pdb --cg Martini
Downloading from Zenodo ... /home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/cg2all/model/Martini.ckpt
Traceback (most recent call last):
  File "/home/tambones/anaconda3/envs/cg2all/bin/convert_cg2all", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/cg2all/script/convert_cg2all.py", line 183, in main
    batch = next(iter(input_s)).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/dgl/heterograph.py", line 5709, in to
    ret._graph = self._graph.copy_to(utils.to_dgl_context(device))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/dgl/heterograph_index.py", line 255, in copy_to
    return _CAPI_DGLHeteroCopyTo(self, ctx.device_type, ctx.device_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dgl/_ffi/_cython/./function.pxi", line 295, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 227, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 217, in dgl._ffi._cy3.core.FuncCall3
dgl._ffi.base.DGLError: [20:54:36] /opt/dgl/src/runtime/cuda/cuda_device_api.cc:343: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: unspecified launch failure
Stack trace:
  [bt] (0) /home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/dgl/libdgl.so(+0x8b08b5) [0x7fbe978b08b5]
  [bt] (1) /home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/dgl/libdgl.so(dgl::runtime::CUDADeviceAPI::CopyDataFromTo(void const*, unsigned long, void*, unsigned long, unsigned long, DGLContext, DGLContext, DGLDataType)+0x82) [0x7fbe978b2d12]
  [bt] (2) /home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::CopyFromTo(DGLArray*, DGLArray*)+0x10d) [0x7fbe977291ed]
  [bt] (3) /home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::CopyTo(DGLContext const&) const+0x103) [0x7fbe97764d53]
  [bt] (4) /home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/dgl/libdgl.so(dgl::UnitGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&)+0x3ff) [0x7fbe97872d4f]
  [bt] (5) /home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/dgl/libdgl.so(dgl::HeteroGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&)+0xf6) [0x7fbe97771596]
  [bt] (6) /home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/dgl/libdgl.so(+0x77ffd6) [0x7fbe9777ffd6]
  [bt] (7) /home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x7fbe9770e278]
  [bt] (8) /home/tambones/anaconda3/envs/cg2all/lib/python3.11/site-packages/dgl/_ffi/_cy3/core.cpython-311-x86_64-linux-gnu.so(+0x1a79f) [0x7fbf292e479f]
```
I would be really grateful for any suggestions.
Best,
Amin

**Comment by huhlim** [comment]
Thank you for your interest on our work. Can you share how did you install the dgl library with cudatoolkit and the version of pytorch? I found the installation is a bit tricky, and the library has a slightly strict compatibility with pytorch...

**Comment by aminsagar** [comment]
Thanks for your response.
I created a new conda environment and installed dgl with
```
conda create --name cg2all pip cudatoolkit=11.3 dgl -c dglteam/label/cu113
```
I repeated the same with 11.6,11.7 and 11.8

```
 conda create --name cg2all pip cudatoolkit dgl git -c dglteam/label/cu118 -c nvidia/label/cuda-11.8.0
conda create --name cg2all pip cudatoolkit dgl git -c dglteam/label/cu117 -c nvidia/label/cuda-11.7.1
conda create --name cg2all pip cudatoolkit dgl git -c dglteam/label/cu116 -c nvidia/label/cuda-11.6.0

```
I also tried installing dgl from the source code using the instructions provided here [https://docs.dgl.ai/install/index.html#install-from-source](https://docs.dgl.ai/install/index.html#install-from-source)

In all cases pytorch is installed while installation of cg2all and is version 1.13.1

```
torch                     1.13.1                   pypi_0    pypi
```

**Comment by huhlim** [comment]
I found that recent versions of dgl (>=1.1) occasionally raise such CUDA errors. DGL library for the CUDA environment seems sensitive to dependent libraries.
When I developed this method, I used dgl=0.9 & cudatoolkit=11.3. And, when I tested the method with dgl=1.0 & cudatoolkit=11.3, it went fine.
I specified the dgl version in the README file. (06885aa524049c16a4edfa1d35acf33ee804b6c2). Please try with dgl=1.0.

**Comment by aminsagar** [comment]
Thanks a lot @huhlim 
It works perfectly with dgl 1.0
